config/routes.rb
RackAcademy::Application.routes.draw do
  root :to => 'lessons#index'

  resources :lessons do
    get :chapters
  end
end

app/models/cached_form.rb
require 'abstract_form'

class CachedForm < AbstractForm
  FORM_SAVE_EXPIRE = 60 * 30

  def save(key)
    key ||= ""
    class_name = self.class.to_s
    cache_key = key + "_" + class_name
    Rails.cache.write(key, self, :expires_in => FORM_SAVE_EXPIRE) 
  end

  def clear(key)
    key ||= ""
    class_name = self.class.to_s
    cache_key = key + "_" + class_name
    Rails.cache.delete(key) 
  end

  def self.load(key)
    class_name = self.class.to_s
    cache_key = key + "_" + class_name
    obj = Rails.cache.read(key)
    return obj unless obj.nil? 
    return self.new
  end

end

app/models/form/lesson.rb
# -*- coding: utf-8 -*-
require 'simple_validator'

class Form::Lesson < CachedForm
  attr_accessor :title, :description, :video, :script, :passcode

  validate :not_blank?,:passcode?

  def not_blank?
  end

  def passcode?
    if passcode != "miko3moemoe"
      errors.add(:passcode,"passcode invalid")
      return
    end
  end

end

app/models/lesson.rb
# -*- coding: utf-8 -*-
require "pp"
class Lesson < ActiveRecord::Base


def chapters

  markdown = Redcarpet::Markdown.new(
    Redcarpet::Render::HTML,
    :autolink => true, 
    :space_after_headers => true, 
    :filter_html => true, 
    :hard_wrap => true,
    :gh_blockcode => true,
    :fenced_code => true,
    )

  results = []
  chapters = self.script.split(">>>>")
  chapters.each do |chapter|
    chapter = ">>>>" + chapter
    re = Regexp.new('>>>>(\d+)') 
    m = re.match(chapter)
    unless m.nil?
      time = m[1]
      chapter = chapter.gsub(">>>>" + time +"\r\n" ,"")
      #pre-processing
      title_re = Regexp.new('^#\s?(.*)\r$')
      title_m = title_re.match(chapter)
      title = ""  
      unless title_m.nil?
        title = title_m[1]
      end
      html = markdown.render(chapter)
      results.push({
        :time => time,
        :title => title,
        :body => html.to_s
      })

    end
  end
  return results
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def current_lesson
    id = params[:lesson_id] || params[:id]
    lesson = Lesson.find_by_id(id)
    return lesson
  end

  def index
    @lessons = Lesson.where(:public => true).order("id DESC")
  end

  def show
    @lesson = current_lesson
    if @lesson.nil?
      return redirect_to root_path
    end
  end

  def chapters
    @lesson = current_lesson
    if @lesson.nil?
      return redirect_to root_path
    end
    results = @lesson.chapters
    return render :json => results.to_json 
  end

  def new
    @lesson_form = Form::Lesson.new(params[:form_lesson])
  end

  def create
    @lesson_form = Form::Lesson.new(params[:form_lesson])
    unless @lesson_form.valid?
      return redirect_to new_lesson_path
    end
    lesson = Lesson.new
    lesson.title = @lesson_form.title
    lesson.description = @lesson_form.description
    lesson.video = @lesson_form.video
    lesson.script = @lesson_form.script
    lesson.public = true
    lesson.save

    return redirect_to lesson_path(lesson)
  end

  def edit
  end

  def update
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
  case level
  when :notice then 'info'
  when :error then 'error'
  when :alert then 'warning'
  end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <%= favicon_link_tag "/favicon.png",{:type => "image/png"} %>
    <title>[Rackアカデミー] Rackhubを使ったプログラミング＆サーバ構築学習サイト</title>
    <script src="http://www.google.com/jsapi"></script>
    <script>
      google.load("swfobject", "2.1");
      google.load("jquery", "1.7.1");
    </script>

    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="brand" href="/">RackAcademy</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "トップページ", root_path  %></li>
                <li><%= link_to "Rackhub", "http://rackhub.net", {:target => "_blank"}  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
          <div class="row">
            <div class="span12">
            <% [:notice, :error, :alert].each do |level| %>
            <% unless flash[level].blank? %>
             <div data-alert="alert" class="alert alert-<%= flash_class(level) %> fade in">
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                <%= content_tag :p, flash[level] %>
              </div>
              <% end %>
            <% end %>
            <%= yield %>
            </div>
           </div>
          </div>
        </div>

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/lessons/edit.html.erb
edit

app/views/lessons/index.html.erb
<div class="hero-unit" style="">
<h1>Rack Academy</h1>
<p></p>
<p>Rackhubを使った開発を学ぶ、Rackアカデミーへようこそ！</p>
</div>

<div class="span8">
<h3>開講中の講座</h3>
<p></p>

<table class="table">
<thead>
  <tr>
    <th>No.</th>
    <th>講座名</th>
    <th>内容</th>
  </tr>
</thead>
<tbody>

<% @lessons.each do |lesson| %>
  <tr>
    <td><%= lesson.id %></td>
    <td><%= link_to lesson.title, lesson_path(lesson.id) %></td>
    <td><%= lesson.description %></td> 
  </tr>
<% end %>


</tbody>
</table>


</div>

<div class="span1"></div>

<div class="span3">
<h3>Rack Academyとは?</h3>
<p></p>
<p>
Rackhubを使った開発を学ぶ、サーバ管理やプログラミング初学者のための学習用コンテンツです。Rack Academyでは、動画と共に進行するテキストを見ながら、実際にRackをオペレーションすることで、簡単に開発のHow to を学ぶことができます。
</p>
<p></p>
<p style="text-align:center;">
<img width="180px" src="http://rackhub.net/assets/logo-05c37c5d56427f413809d6058084154b.png" />
</p>
<p></p>
<h3>共有する</h3>
<p></p>
<p>
<a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= root_url %>" data-text="[Rack Academy] Rackhubでの開発を学ぶ、実践型プログラミング＆サーバ構築学習サイト <%= root_url %> #rackhub" data-lang="ja">ツイート</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-href="<%= root_url %>" data-send="false" data-layout="button_count" data-width="150" data-show-faces="true"></div>



</p>



</div>

app/views/lessons/new.html.erb
<h1>Create Lesson</h1>
<hr />
<%= form_for @lesson_form, :url => lessons_path do |form| %>
  <fieldset>
    <%= form.label :title, "タイトル", :class => "" %>
    <%= form.text_field :title, :class => "" %>
  </fieldset>
  <fieldset>
    <%= form.label :description, "説明", :class => "" %>
    <%= form.text_area :description, :class => "" %>
  </fieldset>
  <fieldset>
    <%= form.label :video, "ビデオID", :class => "" %>
    <%= form.text_field :video, :class => "" %>
  </fieldset>
  <fieldset>
    <%= form.label :script, "スクリプト", :class => "" %>
    <%= form.text_area :script, :class => "" %>
  </fieldset>
  <fieldset>
    <%= form.label :passcode, "パスコード", :class => "" %>
    <%= form.text_field :passcode, :class => "" %>
  </fieldset>
   <div class="">
    <%= form.submit "作成", :class => "" %>
  </div>

<% end %>

app/views/lessons/show.html.erb
<div class="span12">
  <h1><%= @lesson.title %></h1>
  <p></p>
  <p><%= @lesson.description %></p>
</div>
<div class="span6">
<object width="448" height="252">
<param name="movie" value="http://www.youtube.com/v/<%= @lesson.video %>?version=3&hl=ja_JP&enablejsapi=1&playerapiid=ytplayer"></param>
<param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param>
<embed src="http://www.youtube.com/v/<%= @lesson.video %>?version=3&hl=ja_JP&enablejsapi=1&playerapiid=ytplayer" type="application/x-shockwave-flash" width="448" height="252" allowscriptaccess="always" allowfullscreen="true" id="ytplayer"></embed>
</object>
<p></P>
<h3>コメント</h3>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-comments" data-href="<%= lesson_url(@lesson) %>" data-num-posts="2" data-width="448"></div>
<p></p>
<h3>共有する</h3>
<p></p>
<p>
<a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= lesson_url(@lesson) %>" data-text="[Rack Academy] <%= @lesson.title %> <%= lesson_url(@lesson) %> #rackhub" data-lang="ja">ツイート</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-href="<%= lesson_url(@lesson) %>" data-send="false" data-layout="button_count" data-width="150" data-show-faces="true"></div>



</p>

</div>
<div class="span1"></div>
<div class="span5" id="chapter">
Loading...</div>
<script>
var player;
var timeMap =  new Array();;
var chapterList = new Array();;

function onYouTubePlayerReady(playerId) {
  player = document.getElementById(playerId);
  $.get('<%= lesson_chapters_path(@lesson) %>',function(data){
    $.each(data,function(index,chapter){
      chapterList[chapter.time] = chapter;
    });
    var maxTime = player.getDuration()
    lastChapter = -1
    for(var i=0; i<maxTime; i++){
      if(chapterList[i]){
        lastChapter = i
        timeMap[i] = lastChapter
      }else{
        timeMap[i] = lastChapter
      }
    }
    player.playVideo();
    setInterval("displayCheck()",1000);
    $('#chapter').html("");
  });
}

var currentChapter = -1;
function displayCheck(){
    currentTime = parseInt(player.getCurrentTime());
    if(currentTime){
      currentTime = currentTime - 1;
      chapterNumber = timeMap[currentTime];
      if(chapterNumber != currentChapter ){
        $('#chapter').hide();
        if(chapterNumber > 0){ 
          chapter = chapterList[timeMap[currentTime]];
          $('#chapter').html(chapter.body);
        }else{
          $('#chapter').html("");
        }
        $('#chapter').fadeIn("slow");
        currentChapter = chapterNumber;
      }else{
      }
    }
}

</script>

app/views/pages/index.html.erb
This is the top page